import { createContext, useContext, useState, useEffect } from 'react'

const hi = {
  // Landing
  landing_badge: "आवाज़-आधारित उधार ट्रैकर • ऑफ़लाइन भी चलता है",
  landing_title1: "आपकी आवाज़,",
  landing_title2: "आपका खाता.",
  landing_desc: 'टाइप करने की ज़रूरत नहीं. माइक दबाइये, बोलिये — "रमेश को पाँच सौ उधार दिया" — BolKhata बाकी सब संभाल लेगा. हिंग्लिश, हिंदी, English.',
  landing_cta_dukaandaar: "दुकानदार शुरू करें",
  landing_cta_admin: "Admin Login",
  landing_how: "काम कैसे करता है",
  landing_how_sub: "दुकान पर खड़े-खड़े, एक साँस में हिसाब.",
  step1_t: "बोलो", step1_d: "माइक दबाओ, naturally बोलो जैसे ग्राहक से बोलते हो.",
  step2_t: "सुनो", step2_d: "BolKhata नाम, रक़म, type तुरंत समझे.",
  step3_t: "पक्का करो", step3_d: "कार्ड दिखेगा - सही लगे तो tap करो.",
  step4_t: "हो गया", step4_d: "Balance अपने-आप update, register लिखने की ज़रूरत नहीं.",
  pricing_title: "जब ज़रूरत बढ़े, upgrade करो",
  land_nav_how: "कैसे काम करता है",
  land_nav_pricing: "Pricing",
  land_stat_entries: "प्रति entry",
  land_stat_voice: "सिर्फ़ आवाज़",
  land_stat_hinglish: "हिंग्लिश",
  land_demo_today: "आज",
  land_demo_online: "ऑनलाइन",
  land_demo_udhaar: "उधार",
  land_demo_wapas: "वापस",
  land_demo_listening: "सुन रहा हूँ...",
  land_8sec: "8 sec ऑफ़लाइन",
  land_hinglish_auto: "हिंग्लिश Auto",
  land_steps_badge: "चार आसान कदम",
  land_pricing_badge: "आसान Pricing",
  price_note: "/ mahina",
  price_tag_starter: "Starter",
  price_tag_popular: "Popular",
  pf_free_1: "100 voice entries",
  pf_free_2: "ग्राहक सूची",
  pf_free_3: "ऑफ़लाइन + Cash",
  pf_std_1: "500 entries",
  pf_std_2: "हिंग्लिश AI",
  pf_std_3: "ऑफ़लाइन local whisper",
  pf_paid_1: "असीमित entries",
  pf_paid_2: "प्राथमिकता हिंग्लिश",
  pf_paid_3: "UPI QR + Reminder",
  price_cta_free: "Free शुरू करें",
  price_cta_std: "Standard लो",
  price_cta_paid: "Paid लो",
  land_footer: "भारत के दुकानदारों के लिए, आवाज़ से बना खाता.",
  // Nav
  nav_home: "Home", nav_entry: "नई Entry", nav_customers: "ग्राहक सूची", nav_cash: "Cash Counter", nav_billing: "Plan & Billing", nav_profile: "प्रोफ़ाइल",
  nav_overview: "Overview", nav_shops: "दुकानें", nav_subs: "Subscriptions", nav_logs: "Entries & Logs", nav_settings: "सेटिंग्स", nav_config: "Configuration", nav_admin_profile: "मेरी प्रोफ़ाइल", nav_plans: "Plans", nav_payments: "Payments",
  group_dukaan: "दुकान", group_khata: "खाता", group_business: "व्यापार", group_system: "System",
  role_user_panel: "दुकानदार Panel", role_admin_panel: "Admin Panel",
  // Plans & Payments (admin)
  pl_title: "Plans", pl_sub: "Price, limits aur features edit karein — Landing aur Billing pe live dikhte hain",
  pl_save: "Save Plans", pl_price: "Price (₹)", pl_limit: "Entries Limit (-1 = unlimited)", pl_tag: "Tag", pl_active: "Landing pe dikhao", pl_highlight: "Highlight card", pl_features_en: "Features (English, har line ek)", pl_features_hi: "Features (हिंदी, har line ek)",
  pay_title: "Payments", pay_sub: "Razorpay gateway connect karein — real payments ke liye",
  pay_key: "Razorpay Gateway", pay_key_id: "Key ID", pay_secret: "Key Secret", pay_webhook_secret: "Webhook Secret", pay_note: "Razorpay dashboard se leke save karein. Test mode on rakh ke test karein.",
  pay_test_mode: "Test Mode", pay_test: "Test Connection", pay_live: "Live", pay_mock: "Mock", pay_webhook_title: "Webhook URL", pay_webhook_note: "Razorpay dashboard me ye URL set karein — signature verify ke liye",
  pay_mode: "Mode", pay_connected: "Connected", pay_yes: "Yes", pay_no: "No", pay_test_mode_note: "Test mode = mock orders, no real money. Off = live.",
  // Voice Clone (admin XTTS v2)
  vc_status: "Status", vc_active: "Active", vc_choose_audio: "Choose audio file (WAV/MP3)", vc_clone_voice: "Clone Voice", vc_cloning: "Cloning...", vc_test_voice: "Test Voice", vc_testing: "Testing...", vc_reset_sample: "Reset sample", vc_clear: "Clear",
  // Home
  home_welcome: "नमस्ते", home_sub: "आज का हिसाब",
  home_online: "ऑनलाइन sync सक्रिय", home_offline_queue: "{n} ऑफ़लाइन queue",
  stat_total_out: "कुल उधार बाकी", stat_customers: "कुल ग्राहक", stat_plan: "Plan", stat_reminder: "Reminder योग्य",
  plan_monthly: "{tier} • ₹{price}/mo",
  entry_cta: "नई Entry बोलें",
  entries_today: "आज की Entries",
  view_all: "सब देखें",
  no_entries_today: "आज कोई entry नहीं",
  home_entry_none_sub: "माइक दबाइये — हिंग्लिश/हिंदी/English",
  top_baki: "सबसे ज़्यादा बाकी",
  no_customers: "कोई ग्राहक नहीं",
  offline_banner: "Offline • {n} entries queue में, net आते ही sync",
  offline_badge_off: "Offline • {n} queue में",
  offline_badge_pending: "{n} pending sync",
  sync_now: "अभी Sync करें",
  syncing: "Sync हो रहा है...",
  home_insight_heading: "हिसाब समझाओ • इस हफ़्ते",
  home_insight_udhaar: "उधार ₹{amt}",
  home_insight_wapas: "वापस ₹{amt}",
  home_insight_total: "कुल बाकी ₹{amt}",
  home_cash_band: "Cash Band",
  home_recovery: "Recovery:",
  home_chart_title: "पिछले 7 दिन • दिया vs वसूली",
  home_chart_given: "उधार दिया",
  home_chart_received: "वसूली मिली",
  home_empty_hint: "माइक दबाइये — हिंग्लिश/हिंदी/English",
  th_customer: "ग्राहक", th_type: "Type", th_amount: "रक़म", th_time: "समय",
  badge_udhaar: "उधार", badge_wapas: "वापस",
  // Notifications
  notif_title: "सूचनाएँ",
  notif_mark_all: "सभी Read करें",
  notif_empty: "कोई सूचना नहीं",
  notif_plan_limit: "{plan} plan में {used}/{limit} entries इस्तेमाल — upgrade करें",
  notif_due: "{name} का {amount} उधार बाकी है",
  notif_offline_sync: "{n} offline entries queue में हैं",
  notif_admin_pending_subs: "{n} pending subscriptions",
  notif_admin_shops: "{n} सक्रिय दुकानें अभी",
  // Common
  login: "Login", logout: "Logout", save: "Save", cancel: "रद्द करें", delete: "Delete", confirm: "पक्का करें", search_placeholder: "ग्राहक, entries खोजें...",
  common_no_phone: "कोई फ़ोन नहीं",
  common_loading: "Load हो रहा है...",
  common_load_fail: "Load fail",
  common_refresh: "Refresh", common_saving: "Saving...",
  common_owner: "दुकानदार", common_shop: "मेरी दुकान", admin_hq: "BolKhata HQ",
  loader_msg: "BolKhata सोच रहा है",
  pop_yes: "हाँ, पक्का", pop_no: "नहीं", pop_busy: "हो रहा है...",
  pop_theme_pfx: "BolKhata • System Theme: ", pop_light: "Light", pop_dark: "Dark",
  aria_expand: "Sidebar खोलें", aria_collapse: "Sidebar बंद करें", theme_toggle_label: "थीम बदलें",
  back_home: "← Home",
  p404_t: "पेज नहीं मिला", p404_sub: "ग़लत URL है. Home पर वापस जाएँ.",
  // NewEntry
  entry_title: "नई Entry", entry_sub: "माइक दबाइये और बोलिये — हिंग्लिश / हिंदी / English सब चलेगा.",
  ne_idle: "माइक दबाइये — 8 sec तक बोलिये (offline भी चलेगा)",
  ne_listening: "सुन रहा हूँ... बोलिये, फिर बंद करें",
  ne_thinking: "समझ रहा हूँ...",
  ne_confirm_phase: "पक्का करें",
  ne_ai_thinking: "AI समझ रहा है...",
  ne_ai_sub: "हिंग्लिश • हिंदी • English — cinematic",
  ne_pick_heading: "ग्राहक चुनो",
  ne_confirm_heading: "पक्का करें",
  ne_bola: "बोला:",
  ne_lbl_amount: "रक़म",
  ne_lbl_type: "Type",
  ne_bal_minus: "Balance -",
  ne_bal_plus: "Balance +",
  ne_multi_found: "'{name}' नाम से {n} ग्राहक मिले - कौनसा?",
  ne_baki: "{amount} बाकी",
  ne_new_cust: "नया \"{name}\" बनाओ",
  ne_new_cust_sub: "सूची में नहीं है तो नया ग्राहक",
  ne_phone_hint: "Phone hint: {phone} - filter हो रहा है. अगर ग़लत है तो दूसरा चुनो.",
  ne_btn_cancel: "रद्द करें",
  ne_btn_make: "नया बनाओ + ₹{amount}",
  ne_btn_confirm: "पक्का ✓",
  ne_tip: "Tip: अगली बार \"Ramesh Kumar को\" पूरा नाम बोलो, या \"Ramesh 98 वाले को\" - सीधा match होगा.",
  ne_placeholder_card: "Entry यहाँ confirmation card की तरह दिखेगी.",
  ne_placeholder_ex1: "Hinglish: \"रमेश को पाँच सौ उधार दिया\" → रमेश | 500 | उधार",
  ne_placeholder_ex2: "Deduction: \"रमेश से 400 वसूल\" → रमेश | 400 | वापस (-)",
  ne_placeholder_ex3: "Multiple: \"Ramesh\" बोला और 2 Ramesh हैं → picker खुलेगा",
  ne_grahak: "ग्राहक",
  ne_bhasha: "भाषा",
  ne_new_badge: "नया",
  ne_first_balance: "नया ग्राहक बनेगा • पहला balance {amount}",
  ne_flow_tag_wapas: "(वापस)",
  ne_flow_tag_udhaar: "(उधार)",
  ne_overpay: "⚠ वापस रक़म {amount} बाकी {balance} से ज़्यादा - overpay होगा!",
  ne_lbl_name: "ग्राहक का नाम",
  ne_lbl_name_ph: "जैसे: Anil Kirana Supply",
  ne_amount: "रक़म (₹)",
  ne_type: "Type",
  ne_manual_udhaar: "उधार दिया",
  ne_manual_wapas: "वापसी मिली",
  ne_btn_save: "Entry Save करें",
  ne_btn_saving: "Save हो रहा है...",
  ne_status_offline: "Offline Local ✓",
  ne_status_auto: "Auto: Browser → Local → Server",
  ne_whisper_auto: "Whisper Auto",
  ne_demo_mode: "Demo Mode",
  ne_demo: "Demo →",
  ne_download_local: "Local AI download (12MB) - offline के लिए",
  ne_manual_link: "आवाज़ समझ नहीं आई? Manual entry करें →",
  ne_footer_offline: "<b>100% Offline:</b> Net नहीं तो <b>Local Whisper tiny (12MB)</b> से सुनता है - पहली बार net पे download, फिर बिना net हिंग्लिश/हिंदी. Net है तो <b>Browser (fast) → Server Whisper (accurate) → Local</b> auto fallback. Offline parse `dedh/paune` भी local.",
  ne_no_phone: "कोई फ़ोन नहीं",
  ne_btn_no: "नहीं",
  ne_stt_understanding: "समझ रहा हूँ...",
  ne_stt_local_load: "Local AI load...",
  ne_stt_local_model: "Local model load...",
  ne_stt_understand: "समझ रहा {source}...",
  ne_stt_browser_heard: "Browser सुन लिया",
  ne_stt_browser_listen: "Browser सुन रहा...",
  ne_stt_rec_server: "सुन रहा (record)...",
  ne_stt_rec_offline: "Offline सुन रहा...",
  ne_stt_server_send: "Server पे भेज रहा...",
  ne_stt_local_hear: "Local AI से सुन रहा...",
  ne_err_amount_offline: "रक़म समझ नहीं आई — offline में 'रमेश को 500 उधार' साफ़ बोलो",
  ne_err_amount: "रक़म समझ नहीं आई — 'रमेश को 500' बोलो",
  typeLabel: "",
  // CustomerList
  cust_title: "ग्राहक सूची", cust_sub: "सबसे ज़्यादा बाकी वाले सबसे ऊपर.", add_customer: "नया ग्राहक",
  cfl_all: "सभी", cfl_has: "बाकी >0", cfl_high: "High >₹500", cfl_zero: "शून्य",
  cl_search_ph: "नाम/फ़ोन खोजें...",
  cl_lbl_name: "ग्राहक का नाम", cl_ph_name: "जैसे: Priya Traders",
  cl_lbl_phone: "फ़ोन नंबर",
  cl_lbl_balance: "शुरुआती Balance (₹) — अगर पहले से उधार है",
  cl_btn_add: "ग्राहक जोड़ें", cl_btn_add_busy: "जोड़ रहे हैं...",
  cl_empty_t: "अभी कोई ग्राहक नहीं है",
  cl_empty_sub: "पहली entry बोलकर शुरू करें, या \"+ नया ग्राहक\" से manually जोड़ें.",
  cl_btn_first: "पहली Entry बोलें",
  th_phone: "फ़ोन", th_balance: "बाकी Balance",
  cl_view: "देखें →",
  // CustomerDetail
  cd_not_found: "यह ग्राहक नहीं मिला.",
  cd_back_list: "← ग्राहक सूची पर वापस",
  cd_baaki: "बाकी है",
  cd_edit: "Edit", cd_delete: "Delete", cd_remind: "WhatsApp Reminder",
  cd_upi_link: "UPI Pay Link",
  cd_upi_pay: "UPI App से Pay करो",
  cd_upi_sub: "ग्राहक इस link से सीधा pay कर सकता है - WhatsApp में share करो.",
  cd_lbl_name: "ग्राहक का नाम",
  cd_lbl_phone: "फ़ोन नंबर",
  cd_lbl_upi: "ग्राहक UPI ID (optional)",
  cd_btn_update: "Update करें",
  cd_history: "Entry History",
  cd_no_history: "इस ग्राहक की अभी कोई entry नहीं है.",
  cd_delete_confirm: "क्या आप पक्का \"{name}\" को delete करना चाहते हैं?",
  // CashCounter
  cash_title: "Cash Counter - दिन बंद",
  cc_sub: "नोट गिनकर लिखो, हिसाब auto. Offline भी चलेगा.",
  cc_today: "{date} • {received} वापस / {given} उधार आज",
  cc_offline: "Offline",
  cc_note_gino: "नोट गिनो",
  cc_expected_cash: "Expected cash (optional - हिसाब से कितना होना चाहिए)",
  cc_note: "नोट (optional)",
  cc_note_ph: "कुछ याद रखना है?",
  cc_total: "कुल Cash",
  cc_match: "✓ बराबर",
  cc_extra: "+{amount} ज़्यादा",
  cc_less: "{amount} कम",
  cc_save: "Save...",
  cc_close_day: "दिन बंद करें",
  cc_last7: "पिछले 7 दिन",
  cc_no_history: "कोई history नहीं",
  cc_offline_tip_t: "Offline tip:",
  cc_offline_tip_d: "Net न हो तो भी गिनकर save करो, net आते ही auto sync हो जाएगा. नीचे badge देखो.",
  // Billing
  billing_title: "Plan & Billing",
  bl_sub: "अपना plan देखें और ज़रूरत पड़ने पर upgrade करें. Admin ने price <b>₹{price}</b> set किया है — real Razorpay यहीं से चलेगा.",
  bl_plan: "{tier} Plan",
  bl_per_month: "/ महीना",
  bl_used_free: "{used} / {limit} voice entries इस महीने इस्तेमाल हुई (Admin से बदलेगा)",
  bl_used_paid: "असीमित — Paid active, limit {limit}",
  bl_upgrade: "Upgrade करें - 2 options",
  bl_free_copy: "अब Free = 100 entries! Standard या Paid में असीमित जैसा.",
  bl_admin_limit: "(Admin ने limit {limit} की)",
  bl_entries_mo: "{n} entries/महीना",
  bl_offline_cash: "✓ Offline + Cash Counter",
  bl_unlimited: "असीमित entries",
  bl_priority_ai: "✓ प्राथमिकता हिंग्लिश AI",
  bl_popular: "POPULAR",
  bl_mock_pay: "₹{amount} Mock Pay — {tier}",
  bl_mock_card: "Razorpay (mock — {tier})",
  bl_back: "वापस",
  bl_upgrade_btn: "{tier} Upgrade — ₹{amount} Pay",
  bl_process: "Process हो रहा है...",
  bl_process_short: "Process...",
  bl_real_note: "Real Razorpay खुलेगा अगर Admin ने keys लगाई हैं, वरना mock चलेगा.",
  bl_std_active: "✓ Standard active — {limit} entries, offline + cash. Paid में असीमित जाओ!",
  bl_paid_active: "✓ Paid active — असीमित entries, voice हिंग्लिश/हिंदी/English सब चलेगा",
  bl_comparison: "Plan Comparison",
  bl_row_entries: "Entries / महीना",
  bl_row_customers: "ग्राहक सूची & balance",
  bl_row_wa: "WhatsApp reminder",
  bl_row_voice: "Voice — हिंग्लिश/हिंदी/English",
  bl_row_price: "कीमत",
  bl_footer: "Price & limit Admin → Settings से live बदलता है. Postgres पर भी same.",
  bl_history_title: "भुगतान इतिहास",
  bl_history_sub: "आपके पिछले payment और plan upgrades — यहीं दिखते हैं.",
  bl_history_empty: "अभी कोई भुगतान नहीं हुआ है. Upgrade करने पर history यहाँ दिखेगी.",
  bl_history_plan: "प्लान",
  bl_history_amount: "राशि",
  bl_history_status: "स्थिति",
  bl_history_date: "तारीख",
  bl_history_ref: "ऑर्डर ID",
  // Profile
  profile_title: "प्रोफ़ाइल",
  pr_sub: "अपनी दुकान की जानकारी यहाँ update करें. भाषा से voice hint बदलेगा.",
  pr_lbl_shop: "दुकान का नाम",
  pr_lbl_owner: "मालिक का नाम",
  pr_lbl_phone: "फ़ोन नंबर",
  pr_lbl_upi: "UPI ID (payment के लिए)",
  pr_upi_hint: "ग्राहक को UPI QR / link भेजने के लिए. Offline में भी link बनेगा.",
  pr_lbl_lang: "भाषा — Voice के लिए",
  pr_btn_save: "Save करें",
  pr_btn_busy: "Save हो रहा है...",
  pr_dark_t: "Dark Theme",
  pr_dark_sub: "रात में आँखों के लिए आरामदेह",
  pr_wa_t: "WhatsApp Reminder Auto-Suggest",
  pr_wa_sub: "Overdue ग्राहक के लिए suggestion",
  pr_beep_t: "Voice Confirmation आवाज़",
  pr_beep_sub: "Entry save होने पर beep",
  // Admin Overview
  ov_title: "Admin Overview",
  ov_sub: "Complete health check of the BolKhata platform — live from database.",
  ov_all_ok: "सभी सिस्टम normal",
  ov_last_sync: "आख़री sync {time}",
  ov_chart_title: "पिछले 7 दिन की activity",
  ov_chart_entries_lbl: "Entries",
  ov_chart_pay_lbl: "Payments",
  ov_stat_total: "कुल दुकानें",
  ov_stat_active: "सक्रिय दुकानें",
  ov_mrr: "MRR",
  ov_stat_entries: "आज की voice entries",
  ov_stat_parse: "Voice parse सफलता",
  ov_stat_conv: "Free → Paid conversion",
  ov_all_shops: "सभी दुकानें",
  // Admin Shops
  sh_title: "दुकानें",
  sh_sub: "All registered shops on the platform — Manage Active/Inactive and permanent delete here.",
  sh_export: "Export CSV",
  sh_export_soon: "CSV export जल्द आएगा",
  sh_empty: "कोई दुकान नहीं मिली.",
  sh_th_shop: "दुकान", sh_th_plan: "Plan", sh_th_entries: "Entries", sh_th_status: "Status", sh_th_joined: "Joined", sh_th_actions: "Actions",
  sh_view: "देखें",
  sh_make_inactive: "Inactive करें",
  sh_make_active: "Active करें",
  sh_deactivate: "Deactivate",
  sh_activate: "Activate",
  sh_delete: "Delete",
  sh_entries_lbl: "entries",
  sh_activated: "दुकान activate हो गयी ✓",
  sh_deactivated: "दुकान deactivate हो गयी ✓",
  sh_deleted: "दुकान permanently delete हो गयी ✓",
  sh_popup_delete_t: "Permanently Delete?",
  sh_popup_toggle_t_active: "दुकान Deactivate करें?",
  sh_popup_toggle_t_inactive: "दुकान Activate करें?",
  sh_popup_delete_m: "Permanently delete करेंगे? {name} — सारे customers, entries और history हमेशा के लिए erase हो जाएगी. यह undo नहीं होगा. Continue?",
  sh_popup_toggle_m: "{name} को {action} किया जाएगा. Inactive shops login कर सकती हैं पर entries नहीं बना सकती.",
  sh_popup_action_deactivated: "deactivate", sh_popup_action_activated: "activate",
  sh_popup_delete_c: "हाँ, Delete",
  sh_popup_toggle_c_active: "हाँ, Deactivate",
  sh_popup_toggle_c_inactive: "हाँ, Activate",
  sh_cancel: "रद्द करें",
  st_active: "Active", st_inactive: "Inactive",
  // Admin ShopDetail
  sd_not_found: "दुकान नहीं मिली.",
  sd_back: "← दुकानों पर वापस",
  sd_plan: "{tier} Plan",
  sd_delete: "Permanently Delete",
  sd_customers: "ग्राहक",
  sd_entries: "कुल Entries",
  sd_outstanding: "बकाया",
  sd_joined: "कब जुड़ी",
  sd_recent: "हाल की गतिविधि",
  sd_no_activity: "अभी कोई गतिविधि नहीं है.",
  sd_th_time: "समय", sd_th_status: "Status", sd_th_detail: "विवरण",
  sd_parsed_ok: "Parsed OK",
  sd_manual: "Manual Fallback",
  sd_credit: "Credit Given",
  sd_payment: "Payment Received",
  sd_popup_delete_m: "Permanently delete करेंगे? {name} — सारे customers, entries और history हमेशा के लिए erase हो जाएगी. यह undo नहीं होगा.",
  sd_popup_toggle_m: "{name} को {action} किया जाएगा. Inactive shops login कर सकती हैं पर entries नहीं बना सकती.",
  sd_popup_toggle_c: "हाँ, Confirm",
  // Subscriptions
  sub_title: "Subscriptions",
  sub_sub: "All payments processed via Razorpay.",
  sub_empty: "कोई subscription नहीं मिली.",
  sub_th_shop: "Shop ID", sub_th_amount: "रक़म", sub_th_rz: "Razorpay ID", sub_th_status: "Status", sub_th_date: "तारीख",
  // Logs
  logs_bc_admin: "Admin",
  logs_title: "Entries & Logs",
  logs_sub: "Live voice-entry monitoring — {n} total • select करके hard delete करें",
  logs_search: "दुकान / voice text खोजें...",
  logs_selected: "{n} selected",
  logs_hard_delete: "Hard Delete",
  logs_clear: "Clear",
  logs_empty_t: "कोई entry नहीं मिली",
  logs_empty_sub: "दूसरा filter या search आज़माएं",
  logs_th_shop: "दुकान", logs_th_raw: "Raw Voice Text", logs_th_parsed: "Parsed", logs_th_status: "Status", logs_th_time: "समय",
  logs_parsed_ok: "Parsed OK",
  logs_manual: "Manual",
  logs_footer: "{n} entries • {sel} selected",
  logs_footer_note: "Hard delete permanently हटाएगा + balance revert करेगा",
  logs_deleted: "{n} entries hard delete ✓",
  logs_modal_t: "Hard Delete Confirm",
  logs_modal_warn_t: "Permanent delete:",
  logs_modal_warn: "{n} entries हमेशा के लिए delete होंगी और customer balance revert होगा. यह undo नहीं होगा.",
  logs_delete_btn: "Delete {n} permanently",
  logs_deleting: "Deleting...",
  logs_f_manual: "Manual Fallback",
  logs_cancel: "रद्द करें",
  logs_ids: "IDs: ",
  // Settings
  sv_title: "सेटिंग्स",
  sv_sub_a: "Business & Billing — Advanced ",
  sv_sub_b: " में है",
  sv_config_link: "Configuration →",
  sv_save: "Save Changes ✓",
  sv_saving: "Saving...",
  sv_business_h: "Business Rules",
  sv_business_sub: "Applies instantly across the app.",
  sv_free_limit: "Free entries / महीना",
  sv_free_limit_hint: "Free tier limit",
  sv_price: "Paid price ₹ / महीना",
  sv_price_hint: "Same in Razorpay",
  sv_paid_limit: "Paid limit (-1 = unlimited)",
  sv_default_lang: "Default Language",
  sv_jwt: "JWT expiry (min)",
  sv_jwt_hint: "Login validity",
  sv_wa_tmpl: "WhatsApp template — {name} {balance} {shop}",
  sv_auto_reminder: "Auto Reminder",
  sv_maintenance: "Maintenance",
  sv_rz_h: "Razorpay — Billing",
  sv_rz_live: "Live",
  sv_rz_mock: "Mock (free test)",
  sv_rz_sub: "Without keys, mock mode runs — no charge. Add live keys to go live.",
  sv_rz_key: "Key ID (rzp_...)",
  sv_rz_secret: "Key Secret",
  sv_rz_secret_hint: "Shows as **** after save",
  sv_rz_webhook: "Webhook Secret",
  sv_test_rz: "Test Razorpay →",
  sv_testing: "Testing...",
  sv_danger_h: "Danger Zone — Reset All Data",
  sv_danger_a: "This will delete:",
  sv_danger_b: "User shops, Customers, Entries, Reminders, Subscriptions",
  sv_danger_c: "Demo shops (9876543210, 9998887771-74) and Settings will remain safe ✓",
  sv_danger_d: "— demo login will still work. Type",
  sv_danger_e: "then click.",
  sv_btn_reset: "Reset All Data",
  sv_reset_confirm: "RESET",
  sv_type_reset: "Please type RESET",
  sv_reset_confirm_q: "Are you sure you want to delete all data? Shops, customers, entries will be permanently deleted!",
  sv_reset_done: "All data reset ✓",
  sv_rem_day: "Reminder Day", sv_rem_time: "Reminder Time",
  rem_day_mon: "Monday", rem_day_tue: "Tuesday", rem_day_wed: "Wednesday", rem_day_thu: "Thursday", rem_day_fri: "Friday", rem_day_sat: "Saturday", rem_day_sun: "Sunday",
  // Configuration
  cf_title: "Configuration",
  cf_sub: "Advanced integrations — AI, Voice, WhatsApp, OTP",
  cf_save: "Save Configuration",
  cf_saving: "Saving...",
  cf_advanced: "Advanced",
  cf_ai_h: "AI Brain — Entry Parsing",
  cf_ai_sub: "Groq cheap & fast, OpenAI best, local free rule-based. Set Base URL + Key + Model.",
  cf_provider: "Provider",
  cf_base_url: "Base URL",
  cf_model: "Model",
  cf_api_key: "API Key",
  cf_key_none: "No key needed",
  cf_key_masked: "Shows **** after save",
  cf_test_ai: "Test AI →",
  cf_stt_h: "Voice (STT) — Whisper",
  cf_stt_free_t: "Browser Free ✓ — No install",
  cf_stt_free_d: "Chrome Web Speech API — Hinglish auto. Whisper paid alternative.",
  cf_stt_base: "STT Base URL",
  cf_test_stt: "Test STT →",
  cf_wa_h: "WhatsApp",
  cf_wa_phone: "Phone ID / Sender",
  cf_test_wa: "Test WhatsApp →",
  cf_otp_h: "OTP & Auth",
  cf_otp_tmpl: "Template ID",
  cf_otp_exp: "OTP Expiry (min)",
  cf_jwt_exp: "JWT Expiry (min)",
  cf_test_otp: "Test OTP →",
  prov_local: "Local Free (Rule-based) — No key",
  prov_groq: "Groq — Cheap & Fast",
  prov_openai: "OpenAI — Best",
  prov_openrouter: "OpenRouter",
  prov_anthropic: "Anthropic Claude",
  prov_ollama: "Ollama Local",
  prov_custom: "Custom OpenAI-compatible",
  stt_browser: "Browser Free — Chrome (Recommended)",
  stt_openai: "OpenAI Whisper — Paid",
  stt_custom: "Custom STT",
  wa_me: "wa.me Link — Free",
  wa_twilio: "Twilio",
  wa_interakt: "Interakt",
  wa_custom: "Custom",
  wa_disabled: "Disabled",
  otp_dev: "Dev — 1234 Free",
  otp_msg91: "MSG91",
  // Admin Profile
  ap_title: "Admin Profile",
  ap_sub: "अपना नाम, email और password यहाँ update करें. यही credentials से admin login होगा.",
  ap_lbl_name: "नाम (display)",
  ap_lbl_email: "Login Email",
  ap_email_hint: "इस email से admin login होगा. Default: admin@bolkhata.in",
  ap_lbl_password: "नया Password (optional)",
  ap_pw_hint: "खाली छोड़ने पर पुराना password वही रहेगा.",
  ap_btn_save: "Profile Save करें",
  ap_btn_busy: "Save हो रहा है...",
  ap_saved: "Admin profile update हो गयी ✓",
  ap_name_err: "नाम भरें",
  // Login gateway
  lg_q: "कैसे Login करना चाहते हैं?",
  lg_h: "अपना Panel चुनें",
  lg_login: "{title} Login →",
  lg_role_dukaandar: "दुकानदार",
  lg_role_dukaandar_desc: "अपनी दुकान का उधार खाता बोलिए और तुरंत लिखवाइए.",
  lg_role_admin: "Admin",
  lg_role_admin_desc: "पूरे BolKhata platform की दुकानें, billing और health manage करें.",
  // DukaandaarLogin
  dl_tab_login: "Login",
  dl_tab_register: "नई दुकान",
  dl_title_login: "नमस्ते, फिर से स्वागत है",
  dl_title_register: "नई दुकान Register करें",
  dl_sub_login: "अपना registered phone number डालें",
  dl_sub_register: "Phone number से शुरू करें",
  dl_phone: "Phone Number",
  dl_btn_send: "OTP भेजें",
  dl_sending: "भेज रहे हैं...",
  dl_back: "← वापस जाएँ",
  dl_otp_sent: "OTP <b>+91 {phone}</b> पर भेजा गया",
  dl_verify: "Verify & Login",
  dl_verify_busy: "Verify हो रहा है...",
  dl_resend: "OTP दोबारा भेजें",
  dl_resend_in: "OTP दोबारा भेजें ({s}s)",
  dl_toast_otp_sent: "OTP भेजा गया",
  dl_phone_err: "सही 10-अंक का number डालें",
  dl_otp_err: "पूरा OTP डालें",
  // AdminLogin
  al_title: "Admin Login",
  al_sub: "सिर्फ़ authorized BolKhata team के लिए",
  al_email: "Email",
  al_email_ph: "admin email",
  al_email_err: "सही email डालें",
  al_password: "Password",
  al_password_err: "Password ज़रूरी है",
  al_show: "दिखाओ",
  al_hide: "छुपाओ",
  al_forgot: "Password भूल गए?",
  al_btn: "Login",
  al_verify: "Verify हो रहा है...",
  // Onboarding
  ob_title: "अपनी दुकान Set Up करें",
  ob_sub: "बस दो minute — फिर सीधा बोलना शुरू करें",
  ob_lbl_shop: "दुकान का नाम",
  ob_lbl_owner: "आपका नाम",
  ob_lbl_lang: "भाषा चुनें",
  ob_ph_shop: "जैसे: Sharma Kirana Store",
  ob_ph_owner: "जैसे: Ramesh Sharma",
  ob_btn: "शुरू करें →",
  ob_busy: "Set up हो रहा है...",
  ob_welcome: "BolKhata में स्वागत है, {name} ji! 🎉",
  // Toasts
  toast_entry_limit: "Entry limit खत्म — plan upgrade करें",
  toast_offline_parse: "बात समझ नहीं पाए — दोबारा कोशिश करें",
  toast_offline_source: "Offline bhasha पता नहीं चली",
  toast_pick_candidates: "कौनसा ग्राहक? Tap करके चुनें",
  toast_browser_listening: "Browser सुन रहा है — दोबारा 'Listen' दबाएं",
  toast_audio_short: "आवाज़ बहुत छोटी थी — फिर से बोलिए",
  toast_recording_prompt: "अब बोलिए: नाम, रक़म, उधार या भुगतान",
  toast_offline_record: "Offline mode — बोलिए, save offline होगा",
  toast_mic_permission: "Mic permission देना ज़रूरी है",
  toast_local_fail: "Offline save नहीं हो पाया",
  toast_offline_fail: "Offline entry fail हो गयी",
  toast_pick_required: "पहले ग्राहक चुनें",
  toast_offline_limit: "Offline queue भर गयी — plan upgrade करें",
  toast_offline_save: "{name} offline save हो गया",
  toast_entry_saved: "Entry save हो गयी",
  toast_manual_fields: "नाम और रक़म ज़रूरी है",
  toast_customer_name_required: "ग्राहक का नाम ज़रूरी है",
  toast_customer_added: "ग्राहक जुड़ गया",
  toast_customer_detail_saved: "ग्राहक की जानकारी save हुई",
  toast_customer_deleted: "ग्राहक delete हो गया",
  toast_profile_saved: "Profile save हो गयी",
  toast_cash_closed: "Cash counter बंद — {amount} cash मिला",
  toast_queue_pending: "{message}",
  toast_payment_success_mock: "{tier} payment (mock) सफल",
  toast_payment_success_paid: "Payment सफल — plan active!",
  toast_payment_failed: "Payment fail हो गया",
  toast_mock_upgrade: "Mock upgrade active — live payment जल्द आएगी",
  toast_payment_mock: "{tier} payment (mock) सफल",
  toast_settings_saved: "Settings save हो गयी",
  toast_config_saved: "Configuration save हो गयी",
  toast_logged_out: "आप logout हो गए",
}

const en = {
  // Landing
  landing_badge: "Voice-First Credit Tracker • Works Offline",
  landing_title1: "Your Voice,",
  landing_title2: "Your Ledger.",
  landing_desc: 'No typing needed. Tap mic, say — "Give 500 to Ramesh as credit" — BolKhata handles the rest. Hinglish, Hindi, English.',
  landing_cta_dukaandaar: "Start as Shopkeeper",
  landing_cta_admin: "Admin Login",
  landing_how: "How it works",
  landing_how_sub: "Standing at the counter, close your books in one breath.",
  step1_t: "Speak", step1_d: "Tap mic and speak naturally as you talk to customer.",
  step2_t: "Listen", step2_d: "BolKhata instantly understands name, amount, type.",
  step3_t: "Confirm", step3_d: "A card appears - tap to confirm if correct.",
  step4_t: "Done", step4_d: "Balance auto updates, no register needed.",
  pricing_title: "Upgrade when you need more",
  land_nav_how: "How It Works",
  land_nav_pricing: "Pricing",
  land_stat_entries: "Per entry",
  land_stat_voice: "Voice only",
  land_stat_hinglish: "Hinglish",
  land_demo_today: "Today",
  land_demo_online: "Online",
  land_demo_udhaar: "Credit",
  land_demo_wapas: "Received",
  land_demo_listening: "Listening...",
  land_8sec: "8 sec offline",
  land_hinglish_auto: "Hinglish Auto",
  land_steps_badge: "Four Easy Steps",
  land_pricing_badge: "Simple Pricing",
  price_note: "/month",
  price_tag_starter: "Starter",
  price_tag_popular: "Popular",
  pf_free_1: "100 voice entries",
  pf_free_2: "Customer list",
  pf_free_3: "Offline + Cash",
  pf_std_1: "500 entries",
  pf_std_2: "Hinglish AI",
  pf_std_3: "Offline local whisper",
  pf_paid_1: "Unlimited entries",
  pf_paid_2: "Priority Hinglish",
  pf_paid_3: "UPI QR + Reminder",
  price_cta_free: "Start Free",
  price_cta_std: "Get Standard",
  price_cta_paid: "Get Paid",
  land_footer: "For the shopkeepers of Bharat — a ledger built from your voice.",
  nav_home: "Home", nav_entry: "New Entry", nav_customers: "Customers", nav_cash: "Cash Counter", nav_billing: "Plan & Billing", nav_profile: "Profile",
  nav_overview: "Overview", nav_shops: "Shops", nav_subs: "Subscriptions", nav_logs: "Entries & Logs", nav_settings: "Settings", nav_config: "Configuration", nav_admin_profile: "My Profile", nav_plans: "Plans", nav_payments: "Payments",
  group_dukaan: "Shop", group_khata: "Ledger", group_business: "Business", group_system: "System",
  role_user_panel: "Shopkeeper Panel", role_admin_panel: "Admin Panel",
  // Plans & Payments (admin)
  pl_title: "Plans", pl_sub: "Edit price, limits & features — shown live on Landing & Billing",
  pl_save: "Save Plans", pl_price: "Price (₹)", pl_limit: "Entries Limit (-1 = unlimited)", pl_tag: "Tag", pl_active: "Show on landing", pl_highlight: "Highlight card", pl_features_en: "Features (English, one per line)", pl_features_hi: "Features (Hindi, one per line)",
  pay_title: "Payments", pay_sub: "Connect Razorpay gateway — real payments",
  pay_key: "Razorpay Gateway", pay_key_id: "Key ID", pay_secret: "Key Secret", pay_webhook_secret: "Webhook Secret", pay_note: "Get keys from Razorpay dashboard. Keep test mode on while testing.",
  pay_test_mode: "Test Mode", pay_test: "Test Connection", pay_live: "Live", pay_mock: "Mock", pay_webhook_title: "Webhook URL", pay_webhook_note: "Set this URL in the Razorpay dashboard — used to verify signatures",
  pay_mode: "Mode", pay_connected: "Connected", pay_yes: "Yes", pay_no: "No", pay_test_mode_note: "Test mode = mock orders, no real money. Turn off for live.",
  // Voice Clone (admin XTTS v2)
  vc_status: "Status", vc_active: "Active", vc_choose_audio: "Choose audio file (WAV/MP3)", vc_clone_voice: "Clone Voice", vc_cloning: "Cloning...", vc_test_voice: "Test Voice", vc_testing: "Testing...", vc_reset_sample: "Reset sample", vc_clear: "Clear",
  home_welcome: "Hello", home_sub: "Today's summary",
  home_online: "Online sync active", home_offline_queue: "{n} offline queue",
  stat_total_out: "Total outstanding", stat_customers: "Total customers", stat_plan: "Plan", stat_reminder: "Due reminders",
  plan_monthly: "{tier} • ₹{price}/mo",
  entry_cta: "Speak New Entry",
  entries_today: "Today's Entries",
  view_all: "View all",
  no_entries_today: "No entries today",
  home_entry_none_sub: "Tap mic — Hinglish/Hindi/English",
  top_baki: "Top Balances",
  no_customers: "No customers yet",
  offline_banner: "Offline • {n} entries queued, will sync when online",
  offline_badge_off: "Offline • {n} queued",
  offline_badge_pending: "{n} pending sync",
  sync_now: "Sync Now",
  syncing: "Sync...",
  home_insight_heading: "This Week's Breakdown",
  home_insight_udhaar: "Credit ₹{amt}",
  home_insight_wapas: "Received ₹{amt}",
  home_insight_total: "Total due ₹{amt}",
  home_cash_band: "Cash Band",
  home_recovery: "Recovery:",
  home_chart_title: "Last 7 days • Given vs Collected",
  home_chart_given: "Credit given",
  home_chart_received: "Collected",
  home_empty_hint: "Tap mic — Hinglish/Hindi/English",
  th_customer: "Customer", th_type: "Type", th_amount: "Amount", th_time: "Time",
  badge_udhaar: "Given", badge_wapas: "Received",
  notif_title: "Notifications",
  notif_mark_all: "Mark all read",
  notif_empty: "No notifications",
  notif_plan_limit: "{plan} plan: {used}/{limit} entries used — upgrade now",
  notif_due: "{name} owes {amount}",
  notif_offline_sync: "{n} offline entries queued",
  notif_admin_pending_subs: "{n} pending subscriptions",
  notif_admin_shops: "{n} active shops right now",
  login: "Login", logout: "Logout", save: "Save", cancel: "Cancel", delete: "Delete", confirm: "Confirm", search_placeholder: "Search customers, entries...",
  common_no_phone: "No phone",
  common_loading: "Loading...",
  common_load_fail: "Load failed",
  common_refresh: "Refresh", common_saving: "Saving...",
  common_owner: "Shopkeeper", common_shop: "My Shop", admin_hq: "Bolkhata HQ",
  loader_msg: "BolKhata is thinking",
  pop_yes: "Yes, Sure", pop_no: "No", pop_busy: "Processing...",
  pop_theme_pfx: "BolKhata • System Theme: ", pop_light: "Light", pop_dark: "Dark",
  aria_expand: "Expand sidebar", aria_collapse: "Collapse sidebar", theme_toggle_label: "Toggle theme",
  back_home: "← Home",
  p404_t: "Page not found", p404_sub: "Wrong URL. Go back to Home.",
  entry_title: "New Entry", entry_sub: "Tap mic and speak — Hinglish / Hindi / English supported.",
  ne_idle: "Tap mic — speak up to 8 sec (works offline)",
  ne_listening: "Listening... speak now, then stop",
  ne_thinking: "Understanding...",
  ne_confirm_phase: "Confirm",
  ne_ai_thinking: "AI is understanding...",
  ne_ai_sub: "Hinglish • Hindi • English",
  ne_pick_heading: "Pick Customer",
  ne_confirm_heading: "Confirm",
  ne_bola: "Said:",
  ne_lbl_amount: "Amount",
  ne_lbl_type: "Type",
  ne_bal_minus: "Balance -",
  ne_bal_plus: "Balance +",
  ne_multi_found: "Found {n} customers named '{name}' — which one?",
  ne_baki: "{amount} due",
  ne_new_cust: "Create new \"{name}\"",
  ne_new_cust_sub: "Not in list — create new customer",
  ne_phone_hint: "Phone hint: {phone} — filtering. If wrong, pick another.",
  ne_btn_cancel: "Cancel",
  ne_btn_make: "Create + ₹{amount}",
  ne_btn_confirm: "Confirm ✓",
  ne_tip: "Tip: Next time say the full name \"Ramesh Kumar\", or \"Ramesh 98 wale ko\" — instant match.",
  ne_placeholder_card: "Your entry will appear here as a confirmation card.",
  ne_placeholder_ex1: "Hinglish: \"Ramesh ko paanch sau udhaar diya\" → Ramesh | 500 | Credit",
  ne_placeholder_ex2: "Deduction: \"Ramesh se 400 vasool\" → Ramesh | 400 | Received (-)",
  ne_placeholder_ex3: "Multiple: \"Ramesh\" with 2 Rameshs → a picker opens",
  ne_grahak: "Customer",
  ne_bhasha: "Language",
  ne_new_badge: "New",
  ne_first_balance: "New customer • First balance {amount}",
  ne_flow_tag_wapas: "(paid)",
  ne_flow_tag_udhaar: "(credited)",
  ne_overpay: "⚠ Repayment {amount} exceeds due {balance} — overpay!",
  ne_lbl_name: "Customer Name",
  ne_lbl_name_ph: "e.g. Anil Kirana Supply",
  ne_amount: "Amount (₹)",
  ne_type: "Type",
  ne_manual_udhaar: "Gave Credit",
  ne_manual_wapas: "Received",
  ne_btn_save: "Save Entry",
  ne_btn_saving: "Saving...",
  ne_status_offline: "Offline Local ✓",
  ne_status_auto: "Auto: Browser → Local → Server",
  ne_whisper_auto: "Whisper Auto",
  ne_demo_mode: "Demo Mode",
  ne_demo: "Demo →",
  ne_download_local: "Download local AI (12MB) — for offline",
  ne_manual_link: "Voice not understood? Manual entry →",
  ne_footer_offline: "<b>100% Offline:</b> No internet? <b>Local Whisper tiny (12MB)</b> listens — download once online, then Hinglish/Hindi works offline. Online → <b>Browser (fast) → Server Whisper (accurate) → Local</b> auto fallback. Offline parse `dedh/paune` works locally too.",
  ne_no_phone: "No phone",
  ne_btn_no: "No",
  ne_stt_understanding: "Understanding...",
  ne_stt_local_load: "Loading local AI...",
  ne_stt_local_model: "Loading local model...",
  ne_stt_understand: "Understanding {source}...",
  ne_stt_browser_heard: "Browser heard you",
  ne_stt_browser_listen: "Browser listening...",
  ne_stt_rec_server: "Listening (recording)...",
  ne_stt_rec_offline: "Listening offline...",
  ne_stt_server_send: "Sending to server...",
  ne_stt_local_hear: "Listening via local AI...",
  ne_err_amount_offline: "Couldn't catch an amount — offline, say clearly 'Ramesh ko 500 udhaar'",
  ne_err_amount: "Couldn't catch an amount — say 'Ramesh ko 500'",
  typeLabel: "",
  cust_title: "Customers", cust_sub: "Highest due on top.", add_customer: "New Customer",
  cfl_all: "All", cfl_has: "Due >0", cfl_high: "High >₹500", cfl_zero: "Zero",
  cl_search_ph: "Search name/phone...",
  cl_lbl_name: "Customer Name", cl_ph_name: "e.g. Priya Traders",
  cl_lbl_phone: "Phone Number",
  cl_lbl_balance: "Starting Balance (₹) — if any prior credit",
  cl_btn_add: "Add Customer", cl_btn_add_busy: "Adding...",
  cl_empty_t: "No customers yet",
  cl_empty_sub: "Start with your first voice entry, or add manually via \"+ New Customer\".",
  cl_btn_first: "Speak First Entry",
  th_phone: "Phone", th_balance: "Due Balance",
  cl_view: "View →",
  cd_not_found: "Customer not found.",
  cd_back_list: "← Back to Customers",
  cd_baaki: "due",
  cd_edit: "Edit", cd_delete: "Delete", cd_remind: "WhatsApp Reminder",
  cd_upi_link: "UPI Pay Link",
  cd_upi_pay: "Pay via UPI App",
  cd_upi_sub: "Customer can pay directly from this link — share on WhatsApp.",
  cd_lbl_name: "Customer Name",
  cd_lbl_phone: "Phone Number",
  cd_lbl_upi: "Customer UPI ID (optional)",
  cd_btn_update: "Update",
  cd_history: "Entry History",
  cd_no_history: "No entries for this customer yet.",
  cd_delete_confirm: "Are you sure you want to delete \"{name}\"?",
  cash_title: "Cash Counter - End of Day",
  cc_sub: "Count notes, bookkeeping auto. Works offline too.",
  cc_today: "{date} • {received} received / {given} given today",
  cc_offline: "Offline",
  cc_note_gino: "Count notes",
  cc_expected_cash: "Expected cash (optional — per your books)",
  cc_note: "Note (optional)",
  cc_note_ph: "Anything to remember?",
  cc_total: "Total Cash",
  cc_match: "✓ Matching",
  cc_extra: "+{amount} over",
  cc_less: "{amount} short",
  cc_save: "Save...",
  cc_close_day: "Close Day",
  cc_last7: "Last 7 Days",
  cc_no_history: "No history yet",
  cc_offline_tip_t: "Offline tip:",
  cc_offline_tip_d: "Even offline, count and save — auto syncs when online. Check the badge below.",
  billing_title: "Plan & Billing",
  bl_sub: "View your plan and upgrade if needed. Admin set the price to <b>₹{price}</b> — real Razorpay runs from here.",
  bl_plan: "{tier} Plan",
  bl_per_month: "/month",
  bl_used_free: "{used} / {limit} voice entries used this month (changes from Admin)",
  bl_used_paid: "Unlimited — Paid active, limit {limit}",
  bl_upgrade: "Upgrade — 2 options",
  bl_free_copy: "Free now = 100 entries! Go Standard or Paid for more.",
  bl_admin_limit: "(Admin set limit to {limit})",
  bl_entries_mo: "{n} entries/month",
  bl_offline_cash: "✓ Offline + Cash Counter",
  bl_unlimited: "Unlimited entries",
  bl_priority_ai: "✓ Priority Hinglish AI",
  bl_popular: "POPULAR",
  bl_mock_pay: "₹{amount} Mock Pay — {tier}",
  bl_mock_card: "Razorpay (mock — {tier})",
  bl_back: "Back",
  bl_upgrade_btn: "{tier} Upgrade — ₹{amount} Pay",
  bl_process: "Processing...",
  bl_process_short: "Processing...",
  bl_real_note: "Real Razorpay opens if Admin added keys, otherwise mock runs.",
  bl_std_active: "✓ Standard active — {limit} entries, offline + cash. Go Paid for unlimited!",
  bl_paid_active: "✓ Paid active — Unlimited entries, voice Hinglish/Hindi/English all supported",
  bl_comparison: "Plan Comparison",
  bl_row_entries: "Entries / month",
  bl_row_customers: "Customer list & balance",
  bl_row_wa: "WhatsApp reminder",
  bl_row_voice: "Voice — Hinglish/Hindi/English",
  bl_row_price: "Price",
  bl_footer: "Price & limit change live from Admin → Settings. Same on Postgres.",
  bl_history_title: "Payment History",
  bl_history_sub: "Your past payments and plan upgrades shown here.",
  bl_history_empty: "No payments yet. Upgrade to see your history here.",
  bl_history_plan: "Plan",
  bl_history_amount: "Amount",
  bl_history_status: "Status",
  bl_history_date: "Date",
  bl_history_ref: "Order ID",
  profile_title: "Profile",
  pr_sub: "Update your shop details here. Language changes the voice hint.",
  pr_lbl_shop: "Shop Name",
  pr_lbl_owner: "Owner Name",
  pr_lbl_phone: "Phone Number",
  pr_lbl_upi: "UPI ID (for payments)",
  pr_upi_hint: "To send UPI QR / link to customers. Link works offline too.",
  pr_lbl_lang: "Language — for Voice",
  pr_btn_save: "Save",
  pr_btn_busy: "Saving...",
  pr_dark_t: "Dark Theme",
  pr_dark_sub: "Easy on the eyes at night",
  pr_wa_t: "WhatsApp Reminder Auto-Suggest",
  pr_wa_sub: "Suggestion for overdue customers",
  pr_beep_t: "Voice Confirmation Sound",
  pr_beep_sub: "Beep when entry is saved",
  ov_title: "Admin Overview",
  ov_sub: "Complete health check of the BolKhata platform — live from database.",
  ov_all_ok: "All systems normal",
  ov_last_sync: "Last sync {time}",
  ov_chart_title: "Activity — last 7 days",
  ov_chart_entries_lbl: "Entries",
  ov_chart_pay_lbl: "Payments",
  ov_stat_total: "Total Shops",
  ov_stat_active: "Active Shops",
  ov_mrr: "MRR",
  ov_stat_entries: "Voice entries today",
  ov_stat_parse: "Voice parse success",
  ov_stat_conv: "Free → Paid conversion",
  ov_all_shops: "All Shops",
  sh_title: "Shops",
  sh_sub: "All registered shops on the platform — Manage Active/Inactive and permanent delete here.",
  sh_export: "Export CSV",
  sh_export_soon: "CSV export coming soon",
  sh_empty: "No shops found.",
  sh_th_shop: "Shop", sh_th_plan: "Plan", sh_th_entries: "Entries", sh_th_status: "Status", sh_th_joined: "Joined", sh_th_actions: "Actions",
  sh_view: "View",
  sh_make_inactive: "Make Inactive",
  sh_make_active: "Make Active",
  sh_deactivate: "Deactivate",
  sh_activate: "Activate",
  sh_delete: "Delete",
  sh_entries_lbl: "entries",
  sh_activated: "Shop activated successfully ✓",
  sh_deactivated: "Shop deactivated successfully ✓",
  sh_deleted: "Shop permanently deleted ✓",
  sh_popup_delete_t: "Permanently Delete?",
  sh_popup_toggle_t_active: "Deactivate Shop?",
  sh_popup_toggle_t_inactive: "Activate Shop?",
  sh_popup_delete_m: "{name} will be permanently deleted — all customers, entries and history will be erased forever. This cannot be undone. Continue?",
  sh_popup_toggle_m: "{name} will be {action}. Inactive shops can log in but cannot create entries.",
  sh_popup_delete_c: "Yes, Delete",
  sh_popup_toggle_c_active: "Yes, Deactivate",
  sh_popup_toggle_c_inactive: "Yes, Activate",
  sh_popup_action_deactivated: "deactivate", sh_popup_action_activated: "activate",
  sh_cancel: "Cancel",
  st_active: "Active", st_inactive: "Inactive",
  sd_not_found: "Shop not found.",
  sd_back: "← Back to Shops",
  sd_plan: "{tier} Plan",
  sd_delete: "Permanently Delete",
  sd_customers: "Customers",
  sd_entries: "Total Entries",
  sd_outstanding: "Outstanding",
  sd_joined: "Joined On",
  sd_recent: "Recent Activity",
  sd_no_activity: "No activity yet.",
  sd_th_time: "Time", sd_th_status: "Status", sd_th_detail: "Detail",
  sd_parsed_ok: "Parsed OK",
  sd_manual: "Manual Fallback",
  sd_credit: "Credit Given",
  sd_payment: "Payment Received",
  sd_popup_delete_m: "{name} will be permanently deleted — all customers, entries and history will be erased forever. This cannot be undone.",
  sd_popup_toggle_m: "{name} will be {action}. Inactive shops can log in but cannot create entries.",
  sd_popup_toggle_c: "Yes, Confirm",
  sub_title: "Subscriptions",
  sub_sub: "All payments processed via Razorpay.",
  sub_empty: "No subscriptions found.",
  sub_th_shop: "Shop ID", sub_th_amount: "Amount", sub_th_rz: "Razorpay ID", sub_th_status: "Status", sub_th_date: "Date",
  logs_bc_admin: "Admin",
  logs_title: "Entries & Logs",
  logs_sub: "Live voice-entry monitoring — {n} total • select to hard delete",
  logs_search: "Search shop / voice text...",
  logs_selected: "{n} selected",
  logs_hard_delete: "Hard Delete",
  logs_clear: "Clear",
  logs_empty_t: "No entries found",
  logs_empty_sub: "Try another filter or search",
  logs_th_shop: "Shop", logs_th_raw: "Raw Voice Text", logs_th_parsed: "Parsed", logs_th_status: "Status", logs_th_time: "Time",
  logs_parsed_ok: "Parsed OK",
  logs_manual: "Manual",
  logs_footer: "{n} entries • {sel} selected",
  logs_footer_note: "Hard delete will permanently remove + revert balance",
  logs_deleted: "{n} entries hard deleted ✓",
  logs_modal_t: "Hard Delete Confirm",
  logs_modal_warn_t: "Permanent delete:",
  logs_modal_warn: "{n} entries will be permanently deleted and customer balance reverted. This cannot be undone.",
  logs_delete_btn: "Delete {n} permanently",
  logs_deleting: "Deleting...",
  logs_f_manual: "Manual Fallback",
  logs_cancel: "Cancel",
  logs_ids: "IDs: ",
  sv_title: "Settings",
  sv_sub_a: "Business & Billing — Advanced ",
  sv_sub_b: " lives here",
  sv_config_link: "Configuration →",
  sv_save: "Save Changes ✓",
  sv_saving: "Saving...",
  sv_business_h: "Business Rules",
  sv_business_sub: "Applies instantly across the app.",
  sv_free_limit: "Free entries / month",
  sv_free_limit_hint: "Free tier limit",
  sv_price: "Paid price ₹ / month",
  sv_price_hint: "Same in Razorpay",
  sv_paid_limit: "Paid limit (-1 = unlimited)",
  sv_default_lang: "Default Language",
  sv_jwt: "JWT expiry (min)",
  sv_jwt_hint: "Login validity",
  sv_wa_tmpl: "WhatsApp template — {name} {balance} {shop}",
  sv_auto_reminder: "Auto Reminder",
  sv_maintenance: "Maintenance",
  sv_rz_h: "Razorpay — Billing",
  sv_rz_live: "Live",
  sv_rz_mock: "Mock (free test)",
  sv_rz_sub: "Without keys, mock mode runs — no charge. Add live keys to go live.",
  sv_rz_key: "Key ID (rzp_...)",
  sv_rz_secret: "Key Secret",
  sv_rz_secret_hint: "Shows as **** after save",
  sv_rz_webhook: "Webhook Secret",
  sv_test_rz: "Test Razorpay →",
  sv_testing: "Testing...",
  sv_danger_h: "Danger Zone — Reset All Data",
  sv_danger_a: "This will delete:",
  sv_danger_b: "User shops, Customers, Entries, Reminders, Subscriptions",
  sv_danger_c: "Demo shops (9876543210, 9998887771-74) and Settings will remain safe ✓",
  sv_danger_d: "— demo login will still work. Type",
  sv_danger_e: "then click.",
  sv_btn_reset: "Reset All Data",
  sv_rem_day: "Reminder Day", sv_rem_time: "Reminder Time",
  rem_day_mon: "Monday", rem_day_tue: "Tuesday", rem_day_wed: "Wednesday", rem_day_thu: "Thursday", rem_day_fri: "Friday", rem_day_sat: "Saturday", rem_day_sun: "Sunday",
  sv_reset_confirm: "RESET",
  sv_type_reset: "Please type RESET",
  sv_reset_confirm_q: "Are you sure you want to delete all data? Shops, customers, entries will be permanently deleted!",
  sv_reset_done: "All data reset ✓",
  cf_title: "Configuration",
  cf_sub: "Advanced integrations — AI, Voice, WhatsApp, OTP",
  cf_save: "Save Configuration",
  cf_saving: "Saving...",
  cf_advanced: "Advanced",
  cf_ai_h: "AI Brain — Entry Parsing",
  cf_ai_sub: "Groq cheap & fast, OpenAI best, local free rule-based. Set Base URL + Key + Model.",
  cf_provider: "Provider",
  cf_base_url: "Base URL",
  cf_model: "Model",
  cf_api_key: "API Key",
  cf_key_none: "No key needed",
  cf_key_masked: "Shows **** after save",
  cf_test_ai: "Test AI →",
  cf_stt_h: "Voice (STT) — Whisper",
  cf_stt_free_t: "Browser Free ✓ — No install",
  cf_stt_free_d: "Chrome Web Speech API — Hinglish auto. Whisper paid alternative.",
  cf_stt_base: "STT Base URL",
  cf_test_stt: "Test STT →",
  cf_wa_h: "WhatsApp",
  cf_wa_phone: "Phone ID / Sender",
  cf_test_wa: "Test WhatsApp →",
  cf_otp_h: "OTP & Auth",
  cf_otp_tmpl: "Template ID",
  cf_otp_exp: "OTP Expiry (min)",
  cf_jwt_exp: "JWT Expiry (min)",
  cf_test_otp: "Test OTP →",
  prov_local: "Local Free (Rule-based) — No key",
  prov_groq: "Groq — Cheap & Fast",
  prov_openai: "OpenAI — Best",
  prov_openrouter: "OpenRouter",
  prov_anthropic: "Anthropic Claude",
  prov_ollama: "Ollama Local",
  prov_custom: "Custom OpenAI-compatible",
  stt_browser: "Browser Free — Chrome (Recommended)",
  stt_openai: "OpenAI Whisper — Paid",
  stt_custom: "Custom STT",
  wa_me: "wa.me Link — Free",
  wa_twilio: "Twilio",
  wa_interakt: "Interakt",
  wa_custom: "Custom",
  wa_disabled: "Disabled",
  otp_dev: "Dev — 1234 Free",
  otp_msg91: "MSG91",
  ap_title: "Admin Profile",
  ap_sub: "Update your name, email and password here. Admin login uses these credentials.",
  ap_lbl_name: "Name (display)",
  ap_lbl_email: "Login Email",
  ap_email_hint: "Admin login uses this email. Default: admin@bolkhata.in",
  ap_lbl_password: "New Password (optional)",
  ap_pw_hint: "Leave blank to keep the current password.",
  ap_btn_save: "Save Profile",
  ap_btn_busy: "Saving...",
  ap_saved: "Admin profile updated ✓",
  ap_name_err: "Name is required",
  lg_q: "How do you want to log in?",
  lg_h: "Choose Your Panel",
  lg_login: "{title} Login →",
  lg_role_dukaandar: "Shopkeeper",
  lg_role_dukaandar_desc: "Speak your shop's credit ledger and get it recorded instantly.",
  lg_role_admin: "Admin",
  lg_role_admin_desc: "Manage shops, billing and health of the whole BolKhata platform.",
  dl_tab_login: "Login",
  dl_tab_register: "New Shop",
  dl_title_login: "Welcome back",
  dl_title_register: "Register a New Shop",
  dl_sub_login: "Enter your registered phone number",
  dl_sub_register: "Get started with your phone number",
  dl_phone: "Phone Number",
  dl_btn_send: "Send OTP",
  dl_sending: "Sending...",
  dl_back: "← Go back",
  dl_otp_sent: "OTP sent to <b>+91 {phone}</b>",
  dl_verify: "Verify & Login",
  dl_verify_busy: "Verifying...",
  dl_resend: "Resend OTP",
  dl_resend_in: "Resend OTP ({s}s)",
  dl_toast_otp_sent: "OTP sent",
  dl_phone_err: "Enter a valid 10-digit number",
  dl_otp_err: "Enter the full OTP",
  al_title: "Admin Login",
  al_sub: "Only for authorized BolKhata team",
  al_email: "Email",
  al_email_ph: "admin email",
  al_email_err: "Enter a valid email",
  al_password: "Password",
  al_password_err: "Password is required",
  al_show: "SHOW",
  al_hide: "HIDE",
  al_forgot: "Forgot password?",
  al_btn: "Login",
  al_verify: "Verifying...",
  ob_title: "Set Up Your Shop",
  ob_sub: "Just two minutes — then start speaking",
  ob_lbl_shop: "Shop Name",
  ob_lbl_owner: "Your Name",
  ob_lbl_lang: "Choose Language",
  ob_ph_shop: "e.g. Sharma Kirana Store",
  ob_ph_owner: "e.g. Ramesh Sharma",
  ob_btn: "Get Started →",
  ob_busy: "Setting up...",
  ob_welcome: "Welcome to BolKhata, {name}! 🎉",
  // Toasts
  toast_entry_limit: "Entry limit reached — upgrade your plan",
  toast_offline_parse: "Couldn't understand — try again",
  toast_offline_source: "Offline language not detected",
  toast_pick_candidates: "Which customer? Tap to pick",
  toast_browser_listening: "Browser is listening — tap 'Listen' again",
  toast_audio_short: "Audio too short — speak again",
  toast_recording_prompt: "Now speak: name, amount, credit or payment",
  toast_offline_record: "Offline mode — speak, it'll save offline",
  toast_mic_permission: "Mic permission is required",
  toast_local_fail: "Couldn't save offline",
  toast_offline_fail: "Offline entry failed",
  toast_pick_required: "Pick a customer first",
  toast_offline_limit: "Offline queue full — upgrade plan",
  toast_offline_save: "{name} saved offline",
  toast_entry_saved: "Entry saved",
  toast_manual_fields: "Name and amount are required",
  toast_customer_name_required: "Customer name is required",
  toast_customer_added: "Customer added",
  toast_customer_detail_saved: "Customer details saved",
  toast_customer_deleted: "Customer deleted",
  toast_profile_saved: "Profile saved",
  toast_cash_closed: "Cash counter closed — {amount} cash counted",
  toast_queue_pending: "{message}",
  toast_payment_success_mock: "{tier} payment (mock) successful",
  toast_payment_success_paid: "Payment successful — plan active!",
  toast_payment_failed: "Payment failed",
  toast_mock_upgrade: "Mock upgrade active — live payments soon",
  toast_payment_mock: "{tier} payment (mock) successful",
  toast_settings_saved: "Settings saved",
  toast_config_saved: "Configuration saved",
  toast_logged_out: "You have been logged out",
}

const translations = { hi, en }

const backendMsgs = {
  err_already_paid: ["Aap pehle se hi Paid plan pe hain", "You are already on the Paid plan"],
  err_already_std: ["Aap pehle se hi Standard plan pe hain", "You are already on the Standard plan"],
  err_shop_inactive: ["Aapki dukaan Inactive hai - Admin se sampark karein", "Your shop is inactive - contact Admin"],
  err_reminder_cool: ["Abhi reminder bheja tha - 1 ghante baad try karein", "Reminder was just sent - try again in 1 hour"],
  err_amount_range: ["Raqam 1 se 1 lakh ke beech honi chahiye", "Amount must be between 1 and 1 lakh"],
  err_amount_parse: ["Raqam samajh nahi aayi - jaise 'Ramesh ko 500 udhaar diya' boliye", "Could not understand the amount - say e.g. 'Ramesh ko 500 udhaar diya'"],
  err_audio_big: ["Audio bahut bada hai - 10MB se kam bhejein", "Audio too large - send less than 10MB"],
  err_audio_empty: ["Audio khali hai", "Audio is empty"],
  err_otp_too_many_wrong: ["Bahut zyada galat OTP - naya OTP mangwayein", "Too many wrong OTPs - request a new OTP"],
  err_otp_too_fast: ["Bahut zyada OTP request - 10 minute baad try karein", "Too many OTP requests - try again in 10 minutes"],
  err_bad_creds: ["Email ya password galat hai", "Email or password is wrong"],
  err_entry_not_found: ["Entry nahi mili", "Entry not found"],
  err_free_limit: ["Free plan ki entries poori ho gayi - upgrade karein", "Free plan entries finished - please upgrade"],
  err_customer_name_req: ["Grahak ka naam zaroori hai", "Customer name is required"],
  err_customer_not_found: ["Grahak nahi mila", "Customer not found"],
  err_no_udhaar: ["Is grahak ka koi udhaar baaki nahi - reminder ki zaroorat nahi", "This customer has no pending dues - no reminder needed"],
  err_name_long: ["Naam bahut lamba hai", "Name is too long"],
  err_order_not_found: ["Order nahi mila - pehle /create-order karein", "Order not found - first /create-order"],
  err_otp_bad: ["OTP galat ya expire ho gaya hai", "OTP is wrong or has expired"],
  err_paid_limit: ["Paid plan limit reached - admin se contact karein", "Paid plan limit reached - contact admin"],
  err_paid_price: ["Paid price set nahi hai", "Paid price is not configured"],
  err_pay_sign: ["Payment signature galat - verification fail", "Payment signature wrong - verification failed"],
  err_rz_secret: ["Razorpay secret configure nahi hai", "Razorpay secret not configured"],
  err_phone_invalid: ["Sahi 10-ank ka number daalein", "Enter a valid 10-digit number"],
  err_email_invalid: ["Sahi email daalein", "Enter a valid email"],
  err_customer_reselect: ["Chuna hua grahak nahi mila - dobara choose karein", "Selected customer not found - choose again"],
  err_shop_register: ["Shop nahi mila. Pehle 'Nayi Dukaan' se register karein.", "Shop not found. First register from 'New Shop'."],
  err_shop_not_found: ["Shop nahi mili", "Shop not found"],
  err_std_limit: ["Standard plan limit khatam - Paid me upgrade karein", "Standard plan limit finished - upgrade to Paid"],
  err_export_plan: ["CSV export sirf Standard/Paid plans ke liye hai — upgrade karein", "CSV export is only for Standard/Paid plans — upgrade"],
  err_text_empty: ["Text khali hai", "Text is empty"],
  err_tt_fail: ["Transcription fail - dobara try karein ya manual entry karein", "Transcription failed - try again or add manually"],
  err_phone_registered: ["Ye number pehle se registered hai - Login tab istemaal karein", "This number is already registered - use the Login tab"],
  ok_admin_update: ["Admin profile update ho gayi", "Admin profile updated"],
  ok_local_parser: ["Local parser - bina AI ke Hinglish/Hindi/English basic parse chalega, AI se accuracy badhegi", "Local parser - basic Hinglish/Hindi/English parsing works without AI; AI improves accuracy"],
  ok_claude: ["Claude Connected - key valid", "Claude Connected - key valid"],
  ok_whisper: ["Whisper (OpenAI) Connected - key valid", "Whisper (OpenAI) Connected - key valid"],
  ok_wa_me: ["WhatsApp wa.me link - free, click se WhatsApp khulta hai (auto-send nahi)", "WhatsApp wa.me link - free, click opens WhatsApp (no auto-send)"],
  ok_otp_dev: ["OTP Dev mode - hamesha 1234, SMS free, test ke liye best", "OTP Dev mode - always 1234, SMS free, great for testing"],
  warn_rz_keys: ["Razorpay keys khali hain - pehle save karein", "Razorpay keys are empty - save them first"],
  ok_reset_user: ["Reset ho gaya - user ka data deleted, demo dukaan (9876543210) safe hai. Settings safe hai.", "Reset done - user data deleted, demo shop (9876543210) is safe. Settings untouched."],
  ok_reset_all: ["Reset ho gaya - user shops deleted, demo shops (9876543210) safe hain, demo re-created.", "Reset done - user shops deleted, demo shops (9876543210) safe, demo re-created."],
  warn_ai_key: ["AI key khali hai", "AI key is empty"],
  ok_stt_browser: ["Browser Free STT - koi key nahi chahiye", "Browser Free STT - no key needed"],
  warn_otp_keys: ["OTP Base URL / Key khali", "OTP Base URL / Key is empty"],
  warn_stt_key: ["STT key khali hai", "STT key is empty"],
  warn_wa_keys: ["WhatsApp Base URL / Key khali hai", "WhatsApp Base URL / Key is empty"],
  ok_shop_toggled_on: ["Dukaan activate ho gayi", "Shop activated"],
  ok_shop_toggled_off: ["Dukaan deactivate ho gayi", "Shop deactivated"],
  ok_shop_deleted: ["Dukaan delete ho gayi", "Shop deleted"],
}

const LangContext = createContext(null)

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try { return localStorage.getItem('bolkhata_lang') || 'hi' } catch { return 'hi' }
  })
  useEffect(()=>{ try{ localStorage.setItem('bolkhata_lang', lang) }catch{} }, [lang])
  const toggleLang = () => setLang(l => l === 'hi' ? 'en' : 'hi')
  const t = (key, params) => {
    const str = translations[lang]?.[key] ?? translations['hi']?.[key] ?? key
    if (!params) return str
    let out = str
    for (const k in params) out = out.replaceAll(`{${k}}`, params[k])
    return out
  }
  const tl = (msg) => {
    if (typeof msg !== 'string' || !msg) return msg
    if (msg.startsWith('toast_')) return t(msg)
    for (const k in backendMsgs) {
      const [hiStr, enStr] = backendMsgs[k]
      if (msg === hiStr || msg === enStr) return lang === 'hi' ? hiStr : enStr
    }
    return msg
  }
  return <LangContext.Provider value={{ lang, setLang, toggleLang, t, tl }}>{children}</LangContext.Provider>
}
export const useLang = () => useContext(LangContext)